/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiNew;

import helpers.shareHelper;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER NITRO 5
 */
public class hoadonnhanVien extends javax.swing.JDialog {
Vector vecKhongCTKM, vecKHV, vecCTKM, vecEmp;
DefaultTableModel tblModel = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false; //To change body of generated methods, choose Tools | Templates.
        }

    };
SimpleDateFormat ft = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat time = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
    NumberFormat formatter = new DecimalFormat("#,###");
    /**
     * Creates new form hoadonnhanVien
     */
    public hoadonnhanVien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Hóa Đơn Cá Nhân");
        tblHistory.setRowHeight(20);
        btnPrint.setEnabled(false);
         tblModel.addColumn("Mã đơn hàng");
        tblModel.addColumn("Mã sản phẩm");
        tblModel.addColumn("Số lượng (Ly)");
        tblModel.addColumn("Đơn giá (VNĐ)");
        tblModel.addColumn("Tên CTKM");
        tblModel.addColumn("Mã khách hàng");
        tblModel.addColumn("Chiết khấu (%)");
        tblModel.addColumn("Thời gian");
        tblModel.addColumn("Ngày");
        tblModel.addColumn("TK nhân viên");
        tblModel.addColumn("Thành tiền (VNĐ)");
        tblHistory.setModel(tblModel);
        
        txtName.setText(shareHelper.NhanVienDangNhap.getName());
        LoadlbTotal();
        
    }
    
    public void LoadlbTotal() {
        int line = tblHistory.getRowCount();
        int tong = 0;
        for (int i = 0; i < line; i++) {
            String price = (String) tblHistory.getValueAt(i, 10);
            tong += Integer.parseInt(price.replaceAll(",", ""));
        }
        lbTotal.setText(formatter.format(tong) + " VNĐ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHistory.getTableHeader().setReorderingAllowed(false);
        tblHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHistoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHistory);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nhân Viên:");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 204, 0));
        txtName.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Tổng số tiền đã thu được:");

        lbTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(255, 0, 0));
        lbTotal.setText("0 VNĐ");

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_send_to_printer_30px.png"))); // NOI18N
        btnPrint.setText("In");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lbTotal))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtName)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHistoryMouseClicked
        //        try {
            //            // TODO add your handling code here:
            //            int line = tblHistory.getSelectedRow();
            //            cbEmp.setActionCommand(String.valueOf(tblHistory.getValueAt(line, 9)));
            //            Date birthday = ft.parse((String) tblHistory.getValueAt(line, 8));
            //            txtdate.setDate(birthday);
            //        } catch (ParseException ex) {
            //            Logger.getLogger(LichSuJpanl.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_tblHistoryMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
        String connectionUrl = "jdbc:sqlserver://localhost;database=TheOne;";
        String dbusername = "sa";
        String password ="01219164372";
        Connection con = DriverManager.getConnection(connectionUrl,dbusername,password);
        
        
        PreparedStatement pstmt;
        ResultSet rs ;
        
        
        String name = (String) shareHelper.NhanVienDangNhap.getUser();
        if (shareHelper.NhanVienDangNhap.getUser() == null) {
            JOptionPane.showMessageDialog(null, "Tài khoản nhân viên trống.");
            
        } else {
            try {
                pstmt = con.prepareStatement("select * from OrderDetails  join [Order] on OrderDetails.IDOrder=[Order].IDOrder "
                    + "where UsernameEmp ='" + name+ "'");
                rs = pstmt.executeQuery();
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null, "Nhân viên " + name + " chưa bán được sản phẩm nào !");
                    return;
                } else {
                   
                    
                    //select theo khách hàng VIP
                    try {
                        pstmt = con.prepareStatement("select * from OrderDetails  join [Order] on OrderDetails.IDOrder=[Order].IDOrder "
                            + "join Product on OrderDetails.IDProduct=Product.IDProduct "
                            + "join Customer on OrderDetails.CusName=Customer.IDCus  "
                            + "where Orderdetails.CusName != 'Khách vãng lai' and UsernameEmp ='" + name+ "'");
                        rs = pstmt.executeQuery();
                        while (rs.next()) {
                            vecKHV = new Vector();
                            vecKHV.add(rs.getString("IDOrder"));
                            vecKHV.add(rs.getString("IDProduct"));
                            vecKHV.add(rs.getString("Quantity"));
                            vecKHV.add(formatter.format(rs.getInt("Price")));
                            vecKHV.add(rs.getString("NamePromo"));
                            vecKHV.add(rs.getString("CusName"));
                            vecKHV.add(rs.getString("Discount"));
                            vecKHV.add(rs.getString("TimeOrder"));
                            vecKHV.add(rs.getString("DateOrder"));
                            vecKHV.add(rs.getString("UsernameEmp"));
                            int quanKHV = rs.getInt("Quantity");
                            int priceKHV = rs.getInt("Price");
                            int discountKHV = rs.getInt("Discount");
                            int dismoneyKHV = (quanKHV * priceKHV * discountKHV) / 100;
                            int totalKHV = (priceKHV * quanKHV) - dismoneyKHV;
                            vecKHV.add(formatter.format(totalKHV));
                            tblModel.addRow(vecKHV);
                        }
                        tblHistory.setModel(tblModel);
                    } catch (SQLException e) {
                    }
                    //select theo CTKM
                    try {
                        pstmt = con.prepareStatement("select * from OrderDetails join [Order] on OrderDetails.IDOrder=[Order].IDOrder "
                            + "join Product on OrderDetails.IDProduct=Product.IDProduct "
                            + "join Promotions on OrderDetails.NamePromo=Promotions.NamePromo "
                            + "where UsernameEmp ='" + name+ "'");
                        rs = pstmt.executeQuery();
                        while (rs.next()) {
                            vecCTKM = new Vector();
                            vecCTKM.add(rs.getString("IDOrder"));
                            vecCTKM.add(rs.getString("IDProduct"));
                            vecCTKM.add(rs.getString("Quantity"));
                            vecCTKM.add(formatter.format(rs.getInt("Price")));
                            vecCTKM.add(rs.getString("NamePromo"));
                            vecCTKM.add(rs.getString("CusName"));
                            vecCTKM.add(rs.getString("DiscountPromo"));
                            vecCTKM.add(rs.getString("TimeOrder"));
                            vecCTKM.add(rs.getString("DateOrder"));
                            vecCTKM.add(rs.getString("UsernameEmp"));
                            int quanCTKM = rs.getInt("Quantity");
                            int priceCTKM = rs.getInt("Price");
                            int discountCTKM = rs.getInt("DiscountPromo");
                            int dismoneyCTKM = (quanCTKM * priceCTKM * discountCTKM) / 100;
                            int totalCTKM = (priceCTKM * quanCTKM) - dismoneyCTKM;
                            vecCTKM.add(formatter.format(totalCTKM));
                            tblModel.addRow(vecCTKM);
                        }
                        tblHistory.setModel(tblModel);
                    } catch (SQLException ex) {
                    }
                    //select theo không áp dụng CTKM
                    try {
                        pstmt = con.prepareStatement("select * from OrderDetails join [Order] on OrderDetails.IDOrder=[Order].IDOrder "
                            + "join Product on OrderDetails.IDProduct=Product.IDProduct "
                            + "where NamePromo='Không có' and UsernameEmp ='" + name+ "'");
                        rs = pstmt.executeQuery();
                        while (rs.next()) {
                            vecKhongCTKM = new Vector();
                            vecKhongCTKM.add(rs.getString("IDOrder"));
                            vecKhongCTKM.add(rs.getString("IDProduct"));
                            vecKhongCTKM.add(rs.getString("Quantity"));
                            vecKhongCTKM.add(formatter.format(rs.getInt("Price")));
                            vecKhongCTKM.add(rs.getString("NamePromo"));
                            vecKhongCTKM.add(rs.getString("CusName"));
                            vecKhongCTKM.add("0");
                            vecKhongCTKM.add(rs.getString("TimeOrder"));
                            vecKhongCTKM.add(rs.getString("DateOrder"));
                            vecKhongCTKM.add(rs.getString("UsernameEmp"));
                            int quanKhongCTKM = rs.getInt("Quantity");
                            int priceKhongCTKM = rs.getInt("Price");
                            int totalKhongCTKM = priceKhongCTKM * quanKhongCTKM;
                            vecKhongCTKM.add(formatter.format(totalKhongCTKM));
                            tblModel.addRow(vecKhongCTKM);
                        }
                        tblHistory.setModel(tblModel);
                    } catch (SQLException ex) {
                    }
                }
            } catch (SQLException ex) {
            }
        }
//        LoadlbTotal();
        LoadlbTotal();
        con.close();
        
        
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
   
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        //xuat file txt

        //
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://localhost;database=TheOne;";
            String dbusername = "sa";
            String password ="01219164372";
            Connection con = DriverManager.getConnection(connectionUrl,dbusername,password);

            PreparedStatement pstmt ;
            ResultSet rs ;

            File file = new File("History.txt");
            file.delete();
            //Viết vào file txt
            try {
                Date now = new Date();
                Writer b = new BufferedWriter(new OutputStreamWriter(new FileOutputStream("LichSu.txt"), "UTF8"));
                b.write("COFFEE THE ONE\r\n\r\n");
                b.write("Địa chỉ: Đồng Hơi\r\n");
                b.write("SĐT: 0886374063\r\n");
                b.write("Thời gian: " + time.format(now) + "\r\n\r\n");
                b.write("\t\t\t\t\tBẢNG THỐNG KÊ BÁN HÀNG NGÀY " + ft.format(now) + "\r\n");
                b.write("Tài khoản: " + shareHelper.NhanVienDangNhap.getUser()+ "\r\n");
                try {
                    pstmt = con.prepareStatement("Select * from Employee where UsernameEmp=?");
                    pstmt.setString(1, (String) shareHelper.NhanVienDangNhap.getUser());
                    rs = pstmt.executeQuery();
                    if (rs.next()) {
                        b.write("Tên nhân viên: " + rs.getString("NameEmp") + "\r\n\r\n");
                    }
                } catch (SQLException ex) {
                }
                b.write("--------------------------------------------------------------------------------------------------------------------------------\r\n");
                b.write("Mã ĐH\tMã SP\tSố lượng (ly)\tĐơn giá (VNĐ)\tTên CTKM\tMã khách hàng\tChiết khấu (%)\tThời gian\tThành tiền (VNĐ)\r\n");
                b.write("--------------------------------------------------------------------------------------------------------------------------------\r\n");

                int line = tblHistory.getRowCount();
                for (int i = 0; i < line; i++) {
                    String s1 = (String) tblHistory.getValueAt(i, 0);
                    String s2 = (String) tblHistory.getValueAt(i, 1);
                    String s3 = (String) tblHistory.getValueAt(i, 2);
                    String s4 = (String) tblHistory.getValueAt(i, 3);
                    String s5 = (String) tblHistory.getValueAt(i, 4);
                    String MKH = (String) tblHistory.getValueAt(i, 5);
                    String s6;
                    if (!MKH.equals("Khách vãng lai")) {
                        s6 = (String) tblHistory.getValueAt(i, 5) + "\t";
                    } else {
                        s6 = (String) tblHistory.getValueAt(i, 5);
                    }
                    String s7 = (String) tblHistory.getValueAt(i, 6);
                    String s8 = (String) tblHistory.getValueAt(i, 7);
                    String s11 = (String) tblHistory.getValueAt(i, 10);
                    b.write(s1 + "\t" + s2 + "\t" + s3 + "\t\t" + s4 + "\t\t" + s5 + "\t" + s6 + "\t" + s7 + "\t\t" + s8 + "\t" + s11 + "\r\n");
                }
                b.write("--------------------------------------------------------------------------------------------------------------------------------\r\n");
                b.write("\t\t\t\t\t\t\t\t\t\t\t\tTổng tiền: " + lbTotal.getText());
                b.close();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            //Mở file txt
            Runtime run = Runtime.getRuntime();
            try {
                run.exec("notepad LichSu.txt");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }

            con.close();

        } catch (Exception e) {
            //            JOptionPane.showMessageDialog(this, e.getMessage());
            JOptionPane.showMessageDialog(null, "Tìm Kiếm 1 Nhân Viên Rồi Mới Được Xuất");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hoadonnhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hoadonnhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hoadonnhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hoadonnhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                hoadonnhanVien dialog = new hoadonnhanVien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTable tblHistory;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables
}
